# bluecheese
# Copyright (C) 2024 Chris January
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
        include:
          - os: ubuntu-22.04
            qt-archives: icu
          - os: windows-2022
            cxx-compiler: cl
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
      if: matrix.os == 'windows-2022'

    - name: Setup cmake
      uses: lukka/get-cmake@v3.28.1
      with:
        cmakeVersion: '3.21.7'
        ninjaVersion: '1.11.1'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        target: 'desktop'
        setup-python: false
        dir: ${{github.workspace}}
        modules: qtconnectivity qtimageformats
        archives: qtbase qtimageformats qttools ${{matrix.qt-archives}}
        cache: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDEFAULT_STOCKFISH_PATH=stockfish ${{matrix.cxx-compiler && '-DCMAKE_CXX_COMPILER=' || ''}}${{matrix.cxx-compiler}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --prefix ${{github.workspace}}/bluecheese${{github.ref_name && '-' || ''}}${{github.ref_name}}

    - name: Zip
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: bluecheese${{github.ref_name && '-' || ''}}${{github.ref_name}}.zip
        directory: ${{github.workspace}}
        path: bluecheese${{github.ref_name && '-' || ''}}${{github.ref_name}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        generate_release_notes: true
        draft: true
        files: bluecheese${{github.ref_name}} && '-' || ''}}${{github.ref_name}}.zip
